version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - USER_SERVICE_HOST=user-service
      - HOTEL_SERVICE_HOST=hotel-service
      - BOOKING_SERVICE_HOST=booking-service
      - PAYMENT_SERVICE_HOST=payment-service
      - CHAT_BOT_SERVICE_HOST=chat-bot-service

  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development

  hotel-service:
    build:
      context: .
      dockerfile: apps/hotel-service/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development

  booking-service:
    build:
      context: .
      dockerfile: apps/booking-service/Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development

  payment-service:
    build:
      context: .
      dockerfile: apps/payment-service/Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development

  chat-bot-service:
    build:
      context: .
      dockerfile: apps/chat-bot-service/Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development