apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-backend.yaml
  - serviceaccount-chatbot.yaml
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - auth-service/deployment.yaml
  - auth-service/service.yaml
  - booking-service/deployment.yaml
  - booking-service/service.yaml
  - hotel-service/deployment.yaml
  - hotel-service/service.yaml
  - payment-service/deployment.yaml
  - payment-service/service.yaml
  - user-service/deployment.yaml
  - user-service/service.yaml
  - chat-bot-service/deployment.yaml
  - chat-bot-service/service.yaml
  - llm-service/deployment.yaml
  - llm-service/service.yaml
  - n8n/configmap-workflow.yaml
  - n8n/deployment.yaml
  - n8n/service.yaml
